### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by justapythonuser** [space-physics/lowtran#12]
I installed lowtran the way you proposed. However, once I tried to run one of the test scripts, 'import lowtran7' from base.py always raised the error 'DLL load failed'.
Checking the dependencies of lowtran7.*.pyd in Anaconda3/lib/site-packages with dependency walker revealed that python37.dll and also liblowtran7*.dll could not be found.  After copying python37.dll from Anaconda3/ and liblowtran7*.dll from Anaconda3/lib/site-packages/lowtran7/.libs/ in the same folder as lowtran7.*.pyd, everything worked fine. Don't know what caused the problem.
I am running anaconda/python 3.7 on Windows 10.

**Comment by scivision** [comment]
I'm not sure offhand. This is an issue that would be fixed by the possible future refactor to not use f2py.

**Comment by scivision** [comment]
This is now fixed
