### ISSUE TITLE
lowtran7.cp39-win_amd64.pyd missing

### ISSUE THREAD

**Issue by shoste120** [space-physics/lowtran#21]
After succesfully installing lowtran, I was unable to run the test scripts due to a missing module:

ModuleNotFoundError: **\lowtran-main\src\lowtran\lowtran7.cp39-win_amd64.pyd

What could be the cause of this module being missing?

Thank you.

**Comment by scivision** [comment]
The underlying issue is that f2py is too unstable on Windows. On Windows, please use Windows Subsystem for Linux. Thanks for bringing this up.
